# Generated by Django 3.0.2 on 2020-02-10 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Полное наименование организации')),
                ('short_name', models.CharField(max_length=100, verbose_name='Сокращенное наименование')),
                ('manager', models.CharField(max_length=100, verbose_name='ФИО подписанта')),
                ('manager_position', models.CharField(max_length=200, verbose_name='Должность подписанта')),
                ('signature', models.CharField(choices=[('charter', 'Устав'), ('power_of_attorney', 'Доверенность')], default='charter', max_length=17, verbose_name='Основание для подписи')),
            ],
            options={
                'ordering': ['short_name'],
            },
        ),
        migrations.CreateModel(
            name='Construction_object',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line', models.CharField(choices=[('НВЛ', 'Невско-Василеостровская линия'), ('Ф-2', 'Фрунзенский радиус'), ('ЛПЛ', 'Лахтинско-Правобережная линиия'), ('ККЛ', 'Красносельско-Калининская линия'), ('Другое', 'Другое')], max_length=50, verbose_name='Объект строительства')),
                ('requisites', models.TextField(max_length=500, verbose_name='Реквизиты')),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, verbose_name='Номер договора')),
                ('subject_of_contract', models.TextField(max_length=500, verbose_name='Предмет договора')),
                ('contract_time', models.DateField(blank=True, null=True, verbose_name='Срок действия договора')),
                ('date_of_conclusion', models.DateField(blank=True, null=True, verbose_name='Дата заключения договора')),
                ('contract_status', models.CharField(choices=[('s', 'Подписан'), ('o', 'На подписании'), ('c', 'Аннулирован'), ('t', 'Расторгнут')], default='o', max_length=13, verbose_name='Статус договора')),
                ('person', models.CharField(choices=[('1', 'Павлышко Е. С.'), ('2', 'Пуленкова Р. Н.'), ('3', 'Бочков М. А.')], default='Павлышко Е. С.', max_length=20, verbose_name='Контактное лицо ДО')),
                ('constr_object', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Construction_object_constr_object', to='catalog.Construction_object', verbose_name='Объект строительства')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Company_customer', to='catalog.Company', verbose_name='Заказчик')),
                ('executor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Company_executor', to='catalog.Company', verbose_name='Исполнитель')),
            ],
            options={
                'ordering': ['contract_status'],
            },
        ),
    ]
