# Generated by Django 3.0.2 on 2020-02-10 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConstructionObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line', models.CharField(choices=[('НВЛ', 'Невско-Василеостровская линия'), ('Ф-2', 'Фрунзенский радиус'), ('ЛПЛ', 'Лахтинско-Правобережная линиия'), ('ККЛ', 'Красносельско-Калининская линия'), ('Другое', 'Другое')], max_length=50, verbose_name='Объект строительства')),
                ('requisites', models.TextField(max_length=500, verbose_name='Реквизиты')),
            ],
        ),
        migrations.AlterField(
            model_name='contract',
            name='constr_object',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Construction_object_constr_object', to='catalog.ConstructionObject', verbose_name='Объект строительства'),
        ),
        migrations.DeleteModel(
            name='Construction_object',
        ),
    ]
