# Generated by Django 3.0.2 on 2020-02-10 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20200210_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='num_work_note',
            field=models.IntegerField(blank=True, null=True, verbose_name='Номер служебной записки'),
        ),
    ]
