# Generated by Django 3.0.2 on 2020-02-10 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20200210_1541'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='constructionobject',
            options={'ordering': ['line']},
        ),
    ]
