# Generated by Django 3.0.3 on 2020-02-13 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_contract_publish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='publish',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
