# Generated by Django 3.0.2 on 2020-02-16 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_auto_20200216_1311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='company',
            name='manager_position',
        ),
        migrations.RemoveField(
            model_name='company',
            name='signature',
        ),
        migrations.AddField(
            model_name='company',
            name='phone',
            field=models.CharField(default=' ', max_length=100, verbose_name='Контактный телефон'),
        ),
        migrations.CreateModel(
            name='ManagerPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager_name', models.CharField(max_length=100, verbose_name='ФИО подписанта')),
                ('manager_position', models.CharField(max_length=200, verbose_name='Должность подписанта')),
                ('manager_signature', models.CharField(choices=[('charter', 'Устав'), ('power_of_attorney', 'Доверенность')], default='charter', max_length=17, verbose_name='Основание для подписи')),
                ('manager_company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Company_manager_company', to='catalog.Company', verbose_name='Организация')),
            ],
        ),
    ]
