# Generated by Django 3.0.2 on 2020-02-16 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_auto_20200216_1820'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='managerperson',
            options={'ordering': ['manager_position']},
        ),
    ]
