# Generated by Django 3.0.2 on 2020-02-16 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_auto_20200216_1952'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='constructionobject',
            options={'ordering': ['-line']},
        ),
    ]
